version: '3.8'

services:
  db:
    image: postgres
    container_name: bl_pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"

  app:
    build: .
    container_name: bl_service
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

